import '@/styles/globals.css';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import Providers from '@/app/providers';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <div className="max-w-40 h-screen w-full border border-gray-200 relative mx-auto">
          <Providers>
            <div id="portal" />
            {children}
            <ReactQueryDevtools initialIsOpen={false} />
          </Providers>
        </div>
      </body>
    </html>
  );
}
